In [ ]:
# Лабораторна робота 1. Магницький Іван Варіант 20
# Вступ до машинного навчання. Елементи лінійної алгебри.
# Завдання 1. Створіть одновимірний масив (вектор) з сумами кожного числа та його попереднього, починаючи з 1, та виведіть його значення.

# Імпорт бібліотеки NumPy
import numpy as np

# Створюємо масив із чисел від 1 до n
n = 10  # можна змінювати це значення для бажаної кількості елементів
array = np.arange(1, n+1)

# Створюємо масив із сум кожного числа і його попереднього
# Для цього використовуємо зсув масиву і додаємо
sums_array = array + np.roll(array, 1)

# Перший елемент масиву не має попереднього, тому його сумуємо з 0
sums_array[0] = array[0]

# Виводимо результат
print("Початковий масив:", array)
print("Масив сум попереднього і поточного елементів:", sums_array)


Початковий масив: [ 1  2  3  4  5  6  7  8  9 10]
Масив сум попереднього і поточного елементів: [ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# Завдання 2.
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями випадкових дійсних чисел від 1 до 10.

# Створення двовимірного масиву (матриці) розміром 3x3 з випадкових дійсних чисел від 1 до 10
matrix = np.random.uniform(1, 10, (3, 3))

# Виведення результату
print("Матриця 3x3 із випадковими дійсними числами від 1 до 10:")
print(matrix)

Матриця 3x3 із випадковими дійсними числами від 1 до 10:
[[4.27281862 2.86704844 8.60364853]
 [8.83205292 9.28366767 1.18942896]
 [6.7869921  6.93369536 5.88803028]]


In [ ]:
# Завдання 3.
# Створення двовимірного масиву (матриці) розміром 3x3 з випадкових натуральних чисел від 1 до 100
matrix = np.random.randint(1, 101, (3, 3))

# Виведення матриці
print("Матриця 3x3 із випадковими натуральними числами від 1 до 100:")
print(matrix)

# Знаходження мінімального значення в матриці
min_value = np.min(matrix)

# Виведення мінімального значення
print("Мінімальне значення в матриці:", min_value)

Матриця 3x3 із випадковими натуральними числами від 1 до 100:
[[80 66 30]
 [10  6 48]
 [86 99 75]]
Мінімальне значення в матриці: 6


In [ ]:
# Завдання 4.
# Створення двовимірного масиву (матриці) розміром 4x4 з випадкових дійсних чисел від 0 до 1
matrix = np.random.rand(4, 4)

# Виведення матриці
print("Матриця 4x4 із випадковими дійсними числами від 0 до 1:")
print(matrix)

# Знаходження кількості елементів, що більше 0.5
count_greater_than_0_5 = np.sum(matrix > 0.5)

# Виведення результату
print("Кількість елементів, що більше 0.5:", count_greater_than_0_5)

Матриця 4x4 із випадковими дійсними числами від 0 до 1:
[[0.5943603  0.30817631 0.58310261 0.49536543]
 [0.95727763 0.96776515 0.61108203 0.58387777]
 [0.01929996 0.39075862 0.17252798 0.13591419]
 [0.87093179 0.36156858 0.9643816  0.18373964]]
Кількість елементів, що більше 0.5: 8


In [ ]:
# Завдання 5.
# Створення двох одновимірних масивів розміром 4 з випадкових цілих чисел від -10 до 10
array1 = np.random.randint(-10, 11, 4)
array2 = np.random.randint(-10, 11, 4)

# Виведення початкових масивів
print("Перший масив:", array1)
print("Другий масив:", array2)

# Поелементне додавання
addition = array1 + array2
print("Результат поелементного додавання:", addition)

# Поелементне віднімання
subtraction = array1 - array2
print("Результат поелементного віднімання:", subtraction)

# Поелементне множення
multiplication = array1 * array2
print("Результат поелементного множення:", multiplication)

Перший масив: [-7 -3 -8 -3]
Другий масив: [ 0 -1  6 -8]
Результат поелементного додавання: [ -7  -4  -2 -11]
Результат поелементного віднімання: [ -7  -2 -14   5]
Результат поелементного множення: [  0   3 -48  24]


In [ ]:
# Завдання 6
# Створення двох матриць розміром 3x3 з випадкових цілих чисел від 1 до 20
matrix1 = np.random.randint(1, 21, (3, 3))
matrix2 = np.random.randint(1, 21, (3, 3))

# Виведення початкових матриць
print("Перша матриця:")
print(matrix1)
print("\nДруга матриця:")
print(matrix2)

# Матричний добуток (використовуємо np.dot або @)
product_matrix = np.dot(matrix1, matrix2)
# Можна також використовувати: product_matrix = matrix1 @ matrix2

# Виведення результату
print("\nДобуток двох матриць:")
print(product_matrix)

Перша матриця:
[[10 17 11]
 [13  9 16]
 [11 17 10]]

Друга матриця:
[[ 8  1 15]
 [ 7 10 17]
 [19  1 20]]

Добуток двох матриць:
[[408 191 659]
 [471 119 668]
 [397 191 654]]


In [ ]:
# Завдання 7
# Створення матриці розміром 2x3 з випадкових цілих чисел від 1 до 4
matrix1 = np.random.randint(1, 5, (2, 3))

# Створення матриці розміром 3x3 з випадкових цілих чисел від 1 до 4
matrix2 = np.random.randint(1, 5, (3, 3))

# Виведення початкових матриць
print("Перша матриця (2x3):")
print(matrix1)
print("\nДруга матриця (3x3):")
print(matrix2)

# Множення матриць (розмір 2x3 на 3x3)
product_matrix = np.dot(matrix1, matrix2)
# Або можна використовувати оператор @: product_matrix = matrix1 @ matrix2

# Виведення результату
print("\nДобуток матриць:")
print(product_matrix)

Перша матриця (2x3):
[[3 3 4]
 [3 1 1]]

Друга матриця (3x3):
[[1 2 1]
 [1 2 4]
 [1 1 3]]

Добуток матриць:
[[10 16 27]
 [ 5  9 10]]


In [ ]:
# Завдання 8
# Створення матриці розміром 3x3 з випадкових цілих чисел від 1 до 7
matrix = np.random.randint(1, 8, (3, 3))

# Виведення початкової матриці
print("Матриця 3x3:")
print(matrix)

# Перевірка, чи матриця є оборотною (детермінант не дорівнює 0)
determinant = np.linalg.det(matrix)
if determinant != 0:
    # Знаходження оберненої матриці
    inverse_matrix = np.linalg.inv(matrix)
    print("\nОбернена матриця:")
    print(inverse_matrix)
else:
    print("\nМатриця не є оборотною, оскільки її визначник дорівнює 0.")

Матриця 3x3:
[[3 6 7]
 [3 7 3]
 [1 6 4]]

Обернена матриця:
[[ 0.18867925  0.33962264 -0.58490566]
 [-0.16981132  0.09433962  0.22641509]
 [ 0.20754717 -0.22641509  0.05660377]]


In [ ]:
# Завдання 9
# Створення матриці розміром 4x4 з випадкових цілих чисел від 0 до 1
matrix = np.random.randint(0, 2, (4, 4))

# Виведення початкової матриці
print("Матриця 4x4:")
print(matrix)

# Транспонування матриці
transposed_matrix = matrix.T

# Виведення транспонованої матриці
print("\nТранспонована матриця:")
print(transposed_matrix)

Матриця 4x4:
[[0 0 1 0]
 [1 0 0 1]
 [1 1 0 1]
 [0 0 1 1]]

Транспонована матриця:
[[0 1 1 0]
 [0 0 1 0]
 [1 0 0 1]
 [0 1 1 1]]


In [ ]:
# Завдання 10
# Створення матриці розміром 3x4 з випадкових дійсних чисел від 0 до 1
matrix = np.random.rand(3, 4)

# Створення вектора розміром 4x1 з випадкових дійсних чисел від 0 до 1
vector = np.random.rand(4, 1)

# Виведення початкових значень
print("Матриця 3x4:")
print(matrix)
print("\nВектор 4x1:")
print(vector)

# Множення матриці на вектор
product = np.dot(matrix, vector)

# Виведення результату
print("\nДобуток матриці на вектор:")
print(product)

Матриця 3x4:
[[0.36728187 0.73271907 0.58912524 0.18091732]
 [0.73352361 0.74437145 0.28987204 0.03226381]
 [0.39338791 0.60698923 0.99793002 0.62750732]]

Вектор 4x1:
[[0.02820218]
 [0.66033963]
 [0.39795678]
 [0.97512666]]

Добуток матриці на вектор:
[[0.90506528]
 [0.65904278]
 [1.42094558]]


In [ ]:
# Завдання 11

# Створення матриці розміром 2x3 з випадкових дійсних чисел від 0 до 1
matrix = np.random.rand(2, 3)

# Створення вектора розміром 3x1 з випадкових дійсних чисел від 0 до 1
vector = np.random.rand(3, 1)

# Виведення початкових значень
print("Матриця 2x3:")
print(matrix)
print("\nВектор 3x1:")
print(vector)

# Множення матриці на вектор
product = np.dot(matrix, vector)

# Виведення результату
print("\nДобуток матриці на вектор:")
print(product)

Матриця 2x3:
[[0.70617214 0.36366334 0.02017641]
 [0.47595395 0.25062193 0.78462505]]

Вектор 3x1:
[[0.31524696]
 [0.40410704]
 [0.98726913]]

Добуток матриці на вектор:
[[0.38949709]
 [1.02595721]]


In [ ]:
# Завдання 12
# Створення першої матриці розміром 3x3 з випадкових цілих чисел від 1 до 5
matrix1 = np.random.randint(1, 6, (3, 3))

# Створення другої матриці розміром 3x3 з випадкових цілих чисел від 1 до 5
matrix2 = np.random.randint(1, 6, (3, 3))

# Виведення початкових матриць
print("Перша матриця 3x3:")
print(matrix1)
print("\nДруга матриця 3x3:")
print(matrix2)

# Знаходження добутку елементів діагоналі другої матриці
diagonal_elements = np.diagonal(matrix2)  # Отримуємо елементи діагоналі
product = np.prod(diagonal_elements)       # Обчислюємо добуток елементів діагоналі

# Виведення результату
print("\nДобуток елементів діагоналі другої матриці:", product)

Перша матриця 3x3:
[[4 4 2]
 [1 4 3]
 [5 3 1]]

Друга матриця 3x3:
[[5 3 5]
 [5 1 3]
 [5 1 4]]

Добуток елементів діагоналі другої матриці: 20


In [ ]:
# Завдання 13
# Створення першої матриці розміром 4x4 з випадкових цілих чисел від 1 до 5
matrix1 = np.random.randint(1, 6, (4, 4))

# Створення другої матриці розміром 4x4 з випадкових цілих чисел від 1 до 5
matrix2 = np.random.randint(1, 6, (4, 4))

# Виведення початкових матриць
print("Перша матриця 4x4:")
print(matrix1)
print("\nДруга матриця 4x4:")
print(matrix2)

# Знаходження різниці елементів матриць
difference = matrix1 - matrix2

# Виведення результату
print("\nРізниця елементів матриць:")
print(difference)

Перша матриця 4x4:
[[3 5 1 4]
 [5 2 4 3]
 [3 4 3 2]
 [4 1 3 4]]

Друга матриця 4x4:
[[5 4 5 2]
 [3 4 5 2]
 [4 2 5 1]
 [4 3 1 1]]

Різниця елементів матриць:
[[-2  1 -4  2]
 [ 2 -2 -1  1]
 [-1  2 -2  1]
 [ 0 -2  2  3]]


In [ ]:
# Завдання 14
# Створення матриці розміром 3x3 з випадкових цілих чисел від 1 до 10
matrix = np.random.randint(1, 11, (3, 3))

# Виведення початкової матриці
print("Матриця 3x3:")
print(matrix)

# Знаходження найменшого елемента матриці
min_element = np.min(matrix)

# Виведення результату
print("\nНайменший елемент матриці:", min_element)

Матриця 3x3:
[[ 6  2  2]
 [ 6  4 10]
 [ 9  2 10]]

Найменший елемент матриці: 2


In [ ]:
# Завдання 15
# Створення матриці розміром 3x3 з випадкових дійсних чисел від -2 до 2
matrix = np.random.uniform(-2, 2, (3, 3))

# Виведення початкової матриці
print("Матриця 3x3:")
print(matrix)

# Знаходження кількості ненульових елементів в кожному рядку
non_zero_counts = np.count_nonzero(matrix, axis=1)

# Перетворення вектора в стовпчик
non_zero_counts_column = non_zero_counts.reshape(-1, 1)

# Виведення результату
print("\nКількість ненульових елементів в кожному рядку (вектор-стовпчик):")
print(non_zero_counts_column)

Матриця 3x3:
[[ 0.86295482 -0.29261249  1.98202121]
 [ 0.21649359  1.01791419  1.50006098]
 [-1.01099384  0.00769381  1.36605832]]

Кількість ненульових елементів в кожному рядку (вектор-стовпчик):
[[3]
 [3]
 [3]]
